<?php
use Pegasus\BlockConstructor;

/**
 * Default configuration values
 * This is for production, DO NOT EDIT THIS FILE WITH YOUR LOCAL VALUES.
 *
 * If you need to override these values then:
 * 1. Create a folder within the `config` folder with the name of your environment (e.g. `local`)
 * 2. Create a file called `config.php` within that folder
 * 3. Create the values you need to override. Make sure, that you have the same keys in the `config.php` as in the `defaults.php`
 * 4. The values in the `config.php` will be merged with the default values automatically.
 * 5. If you introduce a NEW config value, make sure to add it to the `defaults.php` as well, with the values of the PRODUCTION environment.
 * 6. Ignore the `config.php` in your `.gitignore` file
 *
 * @package Pegasus
 */
return [
    'version' => wp_get_environment_type() === 'local' ? time() : THEME_VERSION,
    'path' => THEME_DIR,
    'uri' => THEME_DIR_URI,
    'env' => wp_get_environment_type(),
    'hmr' => [
        'uri' => THEME_HMR_HOST,
        'client' => THEME_HMR_URI . '/@vite/client',
        'sources' => THEME_HMR_URI . '/assets',
        'active' => wp_get_environment_type() === 'local' && ! is_wp_error(wp_remote_get(THEME_HMR_URI)),
    ],
    'manifest' => [
        'path' => THEME_DIST . '/manifest.json',
    ],
    'block_constructor' => [
        'strategy' => BlockConstructor::STRATEGY_BACKEND_ONLY,
    ],
    'elastic' => [
        'host' => '', // Host of the elastic search. No protocol or port needed.
        'name' => '', // Name of the index (normally project name)
    ],
];
