<?php
namespace Gutenberg\ImageChangeTextSlide;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(ImageChangeTextSlide::class)) {
    /**
     * Class ImageChangeTextSlide
     * @author <Pegasus>
     * @package Gutenberg\ImageChangeTextSlide
     */
    class ImageChangeTextSlide extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_67331f95e5cfa.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());
            $slider = apply_filters('ImageChangeTextSliderId', '');

            if (!$slider) {
                $slider = $this->getId();
                add_filter('ImageChangeTextSliderId', function() use($slider) { return $slider; });
            }

            if (!empty($this->data['block']['is_preview']) && !empty($this->data['image']) && empty(apply_filters('ImageChangeTextSliderImg', ''))) {
                $img = $this->data['image'];
                add_filter('ImageChangeTextSliderImg', function() use($img) { return $img; });
            }

            $this->addData(['slider' => $slider]);

            parent::inflate();
        }
    }
}
