<?php
namespace Gutenberg\ProgrammeGrid;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(ProgrammeGrid::class)) {
    /**
     * Class ProgrammeGrid
     * @author <Pegasus>
     * @package Gutenberg\ProgrammeGrid
     */
    class ProgrammeGrid extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_672dd600135d6.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());

            $currencies = [];
            while( have_rows('currencies', 'option') ) {
                the_row();
                $currencies[] = get_sub_field('currency_code');
            }
            $this->addData(['currencies' => $currencies]);

            parent::inflate();
        }
    }
}
