<?php
namespace Gutenberg\TeamMemberCard;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(TeamMemberCard::class)) {
    /**
     * Class TeamMemberCard
     * @author <Pegasus>
     * @package Gutenberg\TeamMemberCard
     */
    class TeamMemberCard extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_6748773cbc91e.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {

            if (!empty($this->data['team_member'])) {
                $this->addData(['item' => Timber::get_post($this->data['team_member']) ]);
            }
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());
            parent::inflate();
        }
    }
}
