<?php
namespace Gutenberg\Share;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(Share::class)) {
    /**
     * Class Share
     * @author <Pegasus>
     * @package Gutenberg\Share
     */
    class Share extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_67485c7e487ef.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {

            $permalink   = str_replace( '%2F', '/', rawurlencode( get_the_permalink() ) );
			$share_title = rawurlencode( esc_html( get_the_title() ) );

            if (!empty($this->data['links'])) {

                if (in_array('copy', $this->data['links'])) {
                    $this->addData([
                        'copy' => [
                        'name' => __('Copy link', 'pegasus'),
                        'url' => get_the_permalink()
                        ]
                    ]);
                }
                if (in_array('x', $this->data['links'])) {
                    $this->addData([
                        'x' => [
                        'name' => __('On X', 'pegasus'),
                        'url' => "https://x.com/home?status={$share_title}+{$permalink}"
                        ]
                    ]);
                }
                if (in_array('facebook', $this->data['links'])) {
                    $this->addData([
                        'facebook' => [
                        'name' => __('Facebook', 'pegasus'),
                        'url' => "https://www.facebook.com/sharer/sharer.php?u={$permalink}"
                        ]
                    ]);
                }
                if (in_array('linkedin', $this->data['links'])) {
                    $this->addData([
                        'linkedin' => [
                        'name' => __('LinkedIn', 'pegasus'),
                        'url' => "https://www.linkedin.com/shareArticle?mini=true&url={$permalink}&title={$share_title}"
                        ]
                    ]);
                }
                if (in_array('whatsapp', $this->data['links'])) {
                    $this->addData([
                        'whatsapp' => [
                        'name' => __('WhatsApp', 'pegasus'),
                        'url' => "https://api.whatsapp.com/send?text={$share_title}"
                        ]
                    ]);
                }
            }

            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());
            parent::inflate();
        }
    }
}
