<?php
namespace Gutenberg\TeamMemberSlider;

use Plugandplay\Pegasus\PostGridSlider\BasePostGridSlider;
use Timber\Timber;

if (!class_exists(TeamMemberSlider::class)) {
    /**
     * Class TeamMemberSlider
     * @author <Pegasus>
     * @package Gutenberg\TeamMemberSlider
     */
    class TeamMemberSlider extends BasePostGridSlider
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_673de424594dd.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            if($this->fields['how_to_populate'] !== 'automatically') {
                $this->additionalArgs = [
                    'post_type' => get_post_types(['public' => true]),
                ];
                
            }

            $this->addData(['blockId' => $this->getId()]);
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());

            //Only allow arrows at the bottom
            if($this->fields['show_arrows']) {
                $this->fields['arrow_position']['vertical'] = 'bottom';
                $this->fields['arrow_position']['horizontal'] = $this->fields['arrow_position']['horizontal'] ?? 'center';
                $this->fields['arrow_position']['spacing'] = $this->fields['arrow_position']['spacing'] ?? 1;
                $this->fields['arrow_position']['inset'] = $this->fields['arrow_position']['inset'] ?? -5;

                $this->addData([
                    'arrow_position' => $this->fields['arrow_position']
                ]);
            }

            parent::inflate();
        }

                /**
         * getThumbnailClasses
         * @return string
         */
        protected function getThumbnailClasses(): string
        {
            $thumbnailSizeField = $this->getData()['block']['data']['thumbnail_size'] ?? null;

            if (!isset($thumbnailSizeField) || empty($thumbnailSizeField)) {
                return '';
            }

            $classes = '';

            switch ($thumbnailSizeField) {
                case 'original':
                    $classes = 'h-auto';
                    break;
                case 'small':
                    $classes = 'h-0 pb-[50%]';
                    break;
                case 'medium':
                    $classes = 'h-0 pb-[100%]';
                    break;
                case 'large':
                    $classes = 'h-0 pb-[150%]';
                    break;
                default:
                    $classes = 'h-auto';
                    break;
            }
            return $classes;
        }
    }
}
