<?php
namespace Gutenberg\Programme;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(Programme::class)) {
    /**
     * Class Programme
     * @author <Pegasus>
     * @package Gutenberg\Programme
     */
    class Programme extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_672dd6856d2e1.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            $exchange_rates = pegasus_get_currency_exchange_rates();
            $this->addData([
                'exchange_rates' => $exchange_rates,
                'base_currency' => 'CHF' // Assuming CHF is base currency
            ]);
            parent::inflate();
        }
    }
}
