<?php
namespace Gutenberg\TeamHeading;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(TeamHeading::class)) {
    /**
     * Class TeamHeading
     * @author <Pegasus>
     * @package Gutenberg\TeamHeading
     */
    class TeamHeading extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_67e5277c8e413.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {   
            global $post;         
            if ($this->fields['generate_dynamically']) {
                $post_title = get_the_title($post);
                
                $team_categories = wp_get_post_terms($post->ID, 'team-category');
                $role = !empty($team_categories) ? $team_categories[0]->name : '';

                $data = [
                    'title' => get_field('title', $post->ID),
                    'name' => $post_title,
                    'role' => $role
                ];
            } else {
                $data = [
                    'title' => $this->fields['title'],
                    'name' => $this->fields['name'],
                    'role' => $this->fields['role']
                ];
            }
            
            $this->addData($data);
            parent::inflate();
        }
    }
}
