<?php
namespace Gutenberg\AccordionLink;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(AccordionLink::class)) {
    /**
     * Class AccordionLink
     * @author <Pegasus>
     * @package Gutenberg\AccordionLink
     */
    class AccordionLink extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_674f305e71773.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());
            parent::inflate();
            $this->addData([
                'hasBackground' => $this->getBackground(),
            ]);
        }

        /**
         * getBackground
         * @return bool
         * @author philipmarklew
         */
        protected function getBackground(): bool
        {
            $background = $this->getData()['block']['style']['color']['background'] ?? false;
            $gradient = $this->getData()['block']['style']['color']['gradient'] ?? false;
            $backgroundClass = $this->getData()['block']['backgroundColor'] ?? false;

            return $background || $gradient || $backgroundClass;
        }
    }
}
