<?php
namespace Gutenberg\QuoteSlider;

use Plugandplay\Pegasus\PostGridSlider\BasePostGridSlider;
use Timber\Timber;

if (!class_exists(QuoteSlider::class)) {
    /**
     * Class QuoteSlider
     * @author <Pegasus>
     * @package Gutenberg\QuoteSlider
     */
    class QuoteSlider extends BasePostGridSlider
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_673f0e683ef8a.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            $this->additionalArgs['post_type'] = 'quote';
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());

            //Only allow arrows at the bottom
            if(!empty($this->fields['show_arrows'])) {
                $this->fields['arrow_position']['vertical'] = 'bottom';
                $this->fields['arrow_position']['horizontal'] = $this->fields['arrow_position']['horizontal'] ?? 'left';
                $this->fields['arrow_position']['spacing'] = $this->fields['arrow_position']['spacing'] ?? 1;
                $this->fields['arrow_position']['inset'] = $this->fields['arrow_position']['inset'] ?? -5;

                $this->addData([
                    'arrow_position' => $this->fields['arrow_position']
                ]);
            }

            parent::inflate();
        }
    }
}
