<?php
namespace Gutenberg\ImageChangeTextSlider;

use Plugandplay\Pegasus\Core\BaseBlock;
use Timber\Timber;

if (!class_exists(ImageChangeTextSlider::class)) {
    /**
     * Class ImageChangeTextSlider
     * @author <Pegasus>
     * @package Gutenberg\ImageChangeTextSlider
     */
    class ImageChangeTextSlider extends BaseBlock
    {
        /**
        * Returns the acf config. Generated by Pegasus. Do not change this method.
        * @return string[]
        * @author <Pegasus>
        */
        static function getAcf(): array
        {
            $filesName = realpath(static::getPath() . '/../') . 'group_67331f6eb84e0.json';
            if (!file_exists($filesName)) {
                return [];
            }
            try {
                return json_decode(file_get_contents($filesName), true);
            } catch (\Exception $e) {
                return [];
            }
        }

        /**
        * @param array $block
        * @param array $fields
        * @param string $viewTemplate
        * @author <Pegasus>
        */
        public function __construct(array $block, array $fields = [])
        {
            // Custom dependency injection here
            parent::__construct($block, $fields);
        }

        /**
         * @return void
         * @author <Pegasus>
         */
        public function inflate(): void
        {
            // Put you custom application logic here, and load the data into $this->data.
            // You will reach the data in the template: {{ my_field }} or {{ this.getData().my_field }}
            // $this->addData(Timber::context());

            $slider = apply_filters('ImageChangeTextSliderId', '');

            add_filter('ImageChangeTextSliderId', function() { return ''; });

            $this->addData(['slider' => $slider]);

            if (!empty($this->data['block']['is_preview'])) {
                $image = apply_filters('ImageChangeTextSliderImg', '');
                if (!empty($image)) {
                    $this->addData(['image' => $image]);
                }
            }

            parent::inflate();
        }
    }
}
